### ISSUE TITLE
Data documentation

### ISSUE THREAD

**Issue by spestana** [Ribbit-Network/ribbit-network-faq#1]
I am going to start a guide (or guides) about the data that the ribbit network collects. Opening an issue here in the faq repo since that seemed like a good place to start.

This guide could cover things such as (but not limited to):
- details about how the measurements are made
- how the auto-calibration is performed
- caveats about instrument accuracy
- how to interpret the data

I see this as serving a few different purposes (and maybe more than one guide is needed to cover these):
- a readme or metadata about ribbit network data, sample code, research ideas
- caveats about instrument accuracy
- some of the science of measuring CO2 (NDIR, plus atmospheric corrections with temperature and pressure)
- "why does the data look like X"? some explanations about what the data might typically look like (could also help spot data errors, odd sensor placement)

This could eventually be part of a [wiki](https://github.com/Ribbit-Network/ribbit-network-frog-sensor/tree/main/wiki), live alongside the [faq](https://github.com/Ribbit-Network/ribbit-network-faq), and maybe would be nice to see as a readme on the [dashboard](https://github.com/Ribbit-Network/ribbit-network-dashboard) or [main website](https://ribbitnetwork.org/).

**Comment by keenanjohnson** [comment]
Sounds great! That would be a real improvement to the documentation!

**Comment by keenanjohnson** [comment]
@all-contributors please add @spestana for their awesome improvements to the data documentation!

**Comment by keenanjohnson** [comment]
@spestana do you think this is done enough for now to close and create individual issues for new things?

**Comment by spestana** [comment]
> @spestana do you think this is done enough for now to close and create individual issues for new things?

yes, sounds good!
